[package]
name = "pyrin-txscript"
description = "Pyrin txscript engine library"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
blake3.workspace = true
borsh.workspace = true
indexmap.workspace = true
itertools.workspace = true
pyrin-addresses.workspace = true
pyrin-consensus-core.workspace = true
pyrin-hashes.workspace = true
pyrin-txscript-errors.workspace = true
log.workspace = true
parking_lot.workspace = true
rand.workspace = true
secp256k1.workspace = true
serde.workspace = true
sha2.workspace = true
smallvec.workspace = true
thiserror.workspace = true
wasm-bindgen.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
pyo3.workspace = true

[dev-dependencies]
criterion.workspace = true
smallvec.workspace = true
hex.workspace = true
serde_json.workspace = true

[[bench]]
name = "bench"
harness = false
