[package]
name = "pyrin-math"
description = "Pyrin misc math library"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
include.workspace = true
repository.workspace = true

[dependencies]
borsh.workspace = true
faster-hex.workspace = true
js-sys.workspace = true
pyrin-utils.workspace = true
malachite-base.workspace = true
malachite-nz.workspace = true
serde-wasm-bindgen.workspace = true
serde.workspace = true
thiserror.workspace = true
wasm-bindgen.workspace = true
workflow-core.workspace = true
workflow-log.workspace = true
workflow-wasm.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
pyo3.workspace = true

[dev-dependencies]
rand_chacha.workspace = true
criterion.workspace = true

[[bench]]
name = "bench"
harness = false
