#!/bin/bash
set -e

./build-web $@

if [ "$1" == "--keygen" ]; then
    echo "building keygen"
    typedoc --name "Pyrin WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/pyrin-keygen ./build/docs/pyrin-keygen.ts
elif [ "$1" == "--rpc" ]; then
    echo "building rpc"
    typedoc --name "Pyrin WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/pyrin-rpc ./build/docs/pyrin-rpc.ts
elif [ "$1" == "--core" ]; then
    echo "building core"
    typedoc --name "Pyrin WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/pyrin-core ./build/docs/pyrin-core.ts
elif [ "$1" == "--sdk" ]; then
    echo "building full"
    typedoc --name "Pyrin WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/pyrin ./build/docs/pyrin.ts
else
    echo "building keygen"
    typedoc --name "Pyrin WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/pyrin-keygen ./build/docs/pyrin-keygen.ts
    echo "building rpc"
    typedoc --name "Pyrin WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/pyrin-rpc ./build/docs/pyrin-rpc.ts
    echo "building core"
    typedoc --name "Pyrin WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/pyrin-core ./build/docs/pyrin-core.ts
    echo "building full"
    typedoc --name "Pyrin WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/pyrin ./build/docs/pyrin.ts

fi