#!/bin/bash
# This script builds the Rusty Pyrin WASM32 SDK release.

# make the script fail for any failed command
set -e

rm -rf release/*
rm -rf web/*
rm -rf nodejs/*
rm -rf docs/*
rm -rf examples/nodejs/typescript/lib

mkdir -p release/pyrin-wasm32-sdk/web
mkdir -p release/pyrin-wasm32-sdk/nodejs
mkdir -p release/pyrin-wasm32-sdk/docs

# pushd .
# cd ../rpc/wrpc/wasm
# wasm-pack build --target web --out-name pyrin-rpc --out-dir web/pyrin-rpc --features wasm32-sdk $@
# popd

wasm-pack build --weak-refs --target web --out-name pyrin --out-dir web/pyrin-keygen --features wasm32-keygen $@
wasm-pack build --weak-refs --dev --target web --out-name pyrin --out-dir web/pyrin-keygen-dev --features wasm32-keygen $@

wasm-pack build --weak-refs --target web --out-name pyrin --out-dir web/pyrin-rpc --features wasm32-rpc $@
wasm-pack build --weak-refs --dev --target web --out-name pyrin --out-dir web/pyrin-rpc-dev --features wasm32-rpc $@

wasm-pack build --weak-refs --target web --out-name pyrin --out-dir web/pyrin-core --features wasm32-core $@
wasm-pack build --weak-refs --dev --target web --out-name pyrin --out-dir web/pyrin-core-dev --features wasm32-core $@

wasm-pack build --weak-refs --target web --out-name pyrin --out-dir web/pyrin --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target web --out-name pyrin --out-dir web/pyrin-dev --features wasm32-sdk $@

wasm-pack build --weak-refs --target nodejs --out-name pyrin --out-dir nodejs/pyrin --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target nodejs --out-name pyrin --out-dir nodejs/pyrin-dev --features wasm32-sdk $@

# wasm-pack build --target web --dev --out-name pyrin --out-dir build/docs/pyrin --features wasm32-sdk $@
typedoc --name "Pyrin WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/pyrin-keygen ./build/docs/pyrin-keygen.ts
typedoc --name "Pyrin WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/pyrin-rpc ./build/docs/pyrin-rpc.ts
typedoc --name "Pyrin WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/pyrin-core ./build/docs/pyrin-core.ts
typedoc --name "Pyrin WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/pyrin ./build/docs/pyrin.ts

# cp -r ../rpc/wrpc/wasm/web/pyrin-rpc release/pyrin-wasm32-sdk/web/pyrin-rpc
cp -r web/pyrin-keygen release/pyrin-wasm32-sdk/web/pyrin-keygen
cp -r web/pyrin-keygen-dev release/pyrin-wasm32-sdk/web/pyrin-keygen-dev

cp -r web/pyrin-rpc release/pyrin-wasm32-sdk/web/pyrin-rpc
cp -r web/pyrin-rpc-dev release/pyrin-wasm32-sdk/web/pyrin-rpc-dev

cp -r web/pyrin-core release/pyrin-wasm32-sdk/web/pyrin-core
cp -r web/pyrin-core-dev release/pyrin-wasm32-sdk/web/pyrin-core-dev

cp -r web/pyrin release/pyrin-wasm32-sdk/web/pyrin
cp -r web/pyrin-dev release/pyrin-wasm32-sdk/web/pyrin-dev

cp -r nodejs/pyrin release/pyrin-wasm32-sdk/nodejs/pyrin
cp -r nodejs/pyrin-dev release/pyrin-wasm32-sdk/nodejs/pyrin-dev

cp -r docs/pyrin-keygen release/pyrin-wasm32-sdk/docs/pyrin-keygen
cp -r docs/pyrin-rpc release/pyrin-wasm32-sdk/docs/pyrin-rpc
cp -r docs/pyrin-core release/pyrin-wasm32-sdk/docs/pyrin-core
cp -r docs/pyrin release/pyrin-wasm32-sdk/docs/pyrin

mkdir -p release/pyrin-wasm32-sdk/examples/data
cp -r examples/data/.gitignore release/pyrin-wasm32-sdk/examples/data/.gitignore
cp -r examples/nodejs release/pyrin-wasm32-sdk/examples/
cp -r examples/web release/pyrin-wasm32-sdk/examples/
cp -r examples/init.js release/pyrin-wasm32-sdk/examples/
cp -r examples/jsconfig.json release/pyrin-wasm32-sdk/examples/
cp -r examples/package.json release/pyrin-wasm32-sdk/examples/

pushd .
cd release/pyrin-wasm32-sdk/examples
npm install
popd

# tsc release/pyrin-wasm32-sdk/examples/nodejs/typescript/

cp index.html release/pyrin-wasm32-sdk/index.html
cp README.md release/pyrin-wasm32-sdk/README.md
cp CHANGELOG.md release/pyrin-wasm32-sdk/CHANGELOG.md
cp LICENSE release/pyrin-wasm32-sdk/LICENSE

node build/package-sizes.js
cp package-sizes.js release/pyrin-wasm32-sdk/package-sizes.js

pushd .
cd release
zip -q -r pyrin-wasm32-sdk.zip pyrin-wasm32-sdk
popd
